begin;
select plan(48);

select has_function('public', 'can_view_workspace_app', ARRAY['uuid', 'text']);
select has_function('public', 'can_edit_workspace_app', ARRAY['uuid', 'text']);
select has_function('public', 'write_app_state_snapshot', ARRAY['uuid', 'text', 'bigint', 'jsonb', 'text', 'jsonb']);
select ok(to_regclass('public.guest_workspace_import_receipts') is not null, 'guest workspace import receipts table exists');
select has_function('public', 'import_guest_workspace', ARRAY['uuid', 'uuid', 'jsonb']);
select has_function('public', 'count_my_workspace_invitations', ARRAY[]::text[]);
select has_function('public', 'restore_workspace_backup', ARRAY['jsonb', 'text']);
select ok(exists(select 1 from pg_policies where schemaname = 'public' and tablename = 'cash_books' and policyname = 'book viewers read cash books'), 'cash book read policy exists');
select ok(exists(select 1 from pg_policies where schemaname = 'public' and tablename = 'employees' and policyname = 'payroll viewers read employees'), 'payroll employee read policy exists');
select ok(exists(select 1 from pg_policies where schemaname = 'public' and tablename = 'app_state_snapshots' and policyname = 'editors write permitted app snapshots'), 'snapshot editor policy exists');
select ok(exists(select 1 from pg_policies where schemaname = 'public' and tablename = 'audit_events' and policyname = 'owners view audit events'), 'owner audit policy exists');
select has_function('public', 'audit_workspace_event', ARRAY['uuid', 'text', 'uuid', 'text', 'jsonb', 'jsonb']);
select ok(to_regclass('public.system_admins') is not null, 'system_admins table exists');
select ok(to_regclass('public.system_user_controls') is not null, 'system_user_controls table exists');
select ok(to_regclass('public.system_admin_audit_events') is not null, 'system_admin_audit_events table exists');
select ok(to_regclass('public.system_backup_runs') is not null, 'system_backup_runs table exists');
select has_function('public', 'is_system_admin', ARRAY[]::text[]);
select has_function('public', 'system_admin_restore_workspace', ARRAY['uuid', 'jsonb', 'text']);
select ok(to_regclass('public.system_restore_operations') is not null, 'system_restore_operations table exists');
select ok(to_regclass('public.system_restore_workspaces') is not null, 'system_restore_workspaces table exists');
select ok(to_regclass('public.notifications') is not null, 'notifications table exists');
select ok(to_regclass('public.approval_requests') is not null, 'approval_requests table exists');
select has_function('public', 'list_my_notifications', ARRAY['integer']);
select has_function('public', 'mark_notification_read', ARRAY['uuid']);
select has_function('public', 'create_approval_request', ARRAY['uuid', 'text', 'text', 'uuid', 'text', 'jsonb']);
select has_function('public', 'decide_approval_request', ARRAY['uuid', 'text', 'text']);
select has_function('public', 'list_workspace_trash', ARRAY['uuid']);
select has_function('public', 'restore_workspace_trash', ARRAY['text', 'uuid']);
select has_function('public', 'purge_expired_workspace_trash', ARRAY['uuid']);
select has_function('public', 'transfer_workspace_ownership', ARRAY['uuid', 'uuid']);
select has_function('public', 'request_account_deletion', ARRAY['boolean']);
select ok(to_regclass('public.workspace_approval_settings') is not null, 'workspace approval settings table exists');
select has_function('public', 'approval_is_granted', ARRAY['uuid', 'text', 'uuid', 'uuid']);
select has_function('public', 'set_workspace_approval_required', ARRAY['uuid', 'text', 'boolean']);
select has_function('public', 'request_workspace_deletion', ARRAY['uuid']);
select has_function('public', 'cancel_workspace_deletion', ARRAY['uuid']);
select has_function('public', 'get_workspace_deletion_status', ARRAY['uuid']);
select has_function('public', 'list_my_workspace_deletions', ARRAY[]::text[]);
select has_function('public', 'system_admin_schedule_workspace_deletion', ARRAY['uuid', 'uuid']);
select has_function('public', 'system_admin_restore_workspace_deletion', ARRAY['uuid', 'uuid']);
select has_function('public', 'system_admin_schedule_user_deletion', ARRAY['uuid', 'uuid', 'timestamp with time zone']);
select has_function('public', 'system_admin_restore_user_deletion', ARRAY['uuid', 'uuid']);
select has_function('public', 'list_my_workspaces', ARRAY[]::text[]);
select has_function('public', 'set_member_workspace_access', ARRAY['uuid', 'uuid', 'boolean', 'uuid']);
select has_column('public', 'trucks', 'last_mutation_id', 'trucks persist mutation receipts');
select has_column('public', 'truck_owners', 'last_mutation_id', 'truck owners persist mutation receipts');
select has_column('public', 'truck_customers', 'last_mutation_id', 'truck customers persist mutation receipts');
select has_column('public', 'truck_transactions', 'last_mutation_id', 'truck transactions persist mutation receipts');

select * from finish();
rollback;
