import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createActionGate } from '../src/hooks/useAsyncAction';

const sourceRoot = path.resolve('src');
const read = (relativePath: string) => fs.readFileSync(path.join(sourceRoot, relativePath), 'utf8');
const readBackend = (relativePath: string) => fs.readFileSync(path.resolve('../backend', relativePath), 'utf8');

const appFiles = ['apps/book/App.tsx', 'apps/payroll/App.tsx', 'apps/truck/App.tsx'].map(read).join('\n');
assert.doesNotMatch(appFiles, /PersistenceToast|usePersistenceStatus|useCloudSnapshot/);
assert.doesNotMatch(appFiles, /supabase|localStore|offlineStore|app_state_snapshots|syncQueue/);
assert.match(read('lib/repositories/useSnapshotRepository.ts'), /persistSnapshot/);
assert.match(read('lib/repositories/mutationLifecycle.ts'), /persistBeforeQueue/);
assert.match(read('components/AppToast.tsx'), /mathan:toast/);
assert.match(read('components/AppToast.tsx'), /lastKey/);
assert.match(read('components/AppToast.tsx'), /recentPersistence/);
assert.match(read('components/AppToast.tsx'), /mathan:sync-status/);
assert.match(read('components/AppToast.tsx'), /mathan:sync-conflict/);
assert.doesNotMatch(read('components/AppNotificationCenter.tsx'), /mathan:sync-status|mathan:sync-conflict/);
assert.doesNotMatch(read('lib/offlineSync.ts'), /mathan:truck-storage-status/);
assert.doesNotMatch(read('apps/truck/truckRepository.ts'), /mathan:truck-storage-status/);
assert.match(read('components/AppToast.tsx'), /toast\.tone/);
assert.match(read('lib/toast.ts'), /emitSyncStatus/);
assert.match(read('lib/toast.ts'), /emitSyncConflict/);
assert.doesNotMatch(read('lib/mobile.ts'), /@capacitor\/toast/);
assert.doesNotMatch(read('lib/mobile.ts'), /showAppToast|emitToast/);
assert.doesNotMatch(read('lib/offlineSync.ts'), /window\.dispatchEvent\(new CustomEvent/);
assert.doesNotMatch(read('lib/repositories/snapshotRepository.ts'), /window\.dispatchEvent\(new CustomEvent/);
assert.doesNotMatch(read('lib/repositories/useSnapshotRepository.ts'), /window\.dispatchEvent\(new CustomEvent/);
assert.match(read('components/DeleteConfirmModal.tsx'), /successMessage/);
assert.match(read('components/DeleteConfirmModal.tsx'), /tone: 'error'/);
assert.match(read('components/DeleteConfirmModal.tsx'), /Action completed successfully/);
assert.match(read('hooks/useDeleteConfirmation.ts'), /close only after the operation succeeds/);
assert.match(read('hooks/useDeleteConfirmation.ts'), /await request\.onConfirm/);
assert.match(read('apps/truck/useTruckMutations.ts'), /DeleteConfirmationRequest/);
assert.match(read('apps/book/components/DeleteBookModal.tsx'), /successMessage/);
assert.match(read('apps/truck/App.tsx'), /useDeleteConfirmation/);
assert.match(read('apps/truck/App.tsx'), /TruckViewContent/);
assert.doesNotMatch(read('apps/truck/App.tsx'), /<DashboardView|<ExpensesPage|<ManageTrucksPage|<ExportPage/);
assert.match(read('apps/truck/components/TruckViewContent.tsx'), /currentView === 'dashboard'/);
assert.match(read('components/AppConnectivityBanner.tsx'), /useOnlineStatus/);
assert.match(read('components/AppConnectivityBanner.tsx'), /Offline/);
assert.match(read('index.css'), /admin-sidebar \{ width: 240px !important/);
assert.match(read('lib/fileExport.ts'), /createCsv/);
assert.match(read('components/ExportButton.tsx'), /bg-\[#3f4d34\]/);
assert.match(read('components/ExportDialog.tsx'), /Export report/);
assert.match(read('components/ExportDialog.tsx'), /<AppSelect/);
assert.match(read('components/ExportDialog.tsx'), /Preview/);
assert.match(read('lib/exports/datePresets.ts'), /weekly/);
assert.match(read('lib/exports/exportMetadata.ts'), /Company/);
assert.match(read('lib/exports/pdfExporter.ts'), /report.headers/);
assert.match(read('apps/book/cashBookExport.ts'), /Opening balance/);
assert.match(read('apps/book/cashBookExport.ts'), /Final balance/);
assert.match(read('lib/exports/dateFormatting.ts'), /formatExportDate/);
assert.match(read('lib/mobile.ts'), /const columnWidth = width \/ labels.length/);
assert.doesNotMatch(read('lib/mobile.ts'), /includes\('transaction'\)/);
assert.match(read('apps/book/App.tsx'), /buildCashBookExportReports/);
assert.match(read('apps/payroll/App.tsx'), /buildPayrollExportReports/);
assert.equal(fs.existsSync(path.join(sourceRoot, 'apps/truck/components/Pages/ExportPage.tsx')), false);
assert.equal(fs.existsSync(path.join(sourceRoot, 'apps/truck/components/Modals/ExportModal.tsx')), false);
assert.equal(fs.existsSync(path.join(sourceRoot, 'apps/payroll/components/PayrollReportModal.tsx')), false);
assert.equal(fs.existsSync(path.join(sourceRoot, 'apps/payroll/components/TransactionsList.tsx')), false);
assert.match(read('lib/exports/exportService.ts'), /exportReport/);
assert.match(read('lib/exports/exportTypes.ts'), /ExportContext/);
assert.match(read('components/ExportDialog.tsx'), /context\.reportName/);
assert.doesNotMatch(read('apps/book/components/Header.tsx'), /ExportButton/);
assert.doesNotMatch(read('apps/payroll/components/TopNavbar.tsx'), /ExportButton/);
assert.doesNotMatch(read('apps/truck/components/TopHeader.tsx'), /ExportButton/);
assert.doesNotMatch(read('apps/payroll/components/Header.tsx'), /Export Payroll|ExportButton|onOpenExportModal/);
assert.match(read('apps/book/components/BookDetailView.tsx'), /ExportButton/);
assert.match(read('apps/book/components/BookDetailView.tsx'), /OPENING BALANCE/);
assert.match(read('apps/book/components/BookDetailView.tsx'), /book\.openingBalance \?\? 0/);
assert.match(read('apps/book/components/BookDetailView.tsx'), /NET BALANCE/);
assert.match(read('apps/payroll/views/ReportsView.tsx'), /ExportButton/);
assert.match(read('apps/payroll/views/TransactionsView.tsx'), /ExportButton/);
assert.match(read('apps/truck/components/Pages/CashReportView.tsx'), /ExportButton/);
assert.match(read('apps/truck/components/ReportsView.tsx'), /ExportButton/);
assert.match(read('apps/truck/components/LedgerHistoryView.tsx'), /ExportButton/);
assert.match(read('components/CompanySelector.tsx'), /useAsyncAction/);
assert.match(read('lib/repositories/snapshotRepository.ts'), /snapshotTails/);
assert.match(read('lib/repositories/snapshotRepository.ts'), /relevant\.length > 0/);
assert.match(read('lib/repositories/personalDataRepository.ts'), /loadPersonalDataArchive/);
assert.match(read('components/SettingsPage.tsx'), /loadPersonalDataArchive/);
assert.doesNotMatch(read('components/SettingsPage.tsx'), /supabase\.from\('(app_state_snapshots|trucks|truck_owners|truck_transactions)'\)/);
assert.doesNotMatch(read('components/CompanySelector.tsx'), /window\.confirm/);
assert.doesNotMatch(read('components/SettingsPage.tsx'), /window\.confirm/);
assert.match(read('hooks/useAsyncAction.ts'), /gate\.current/);
assert.match(read('hooks/useAsyncAction.ts'), /runAction/);
assert.match(read('hooks/useAsyncAction.ts'), /tone: 'success'/);
assert.match(read('hooks/useAsyncAction.ts'), /tone: 'error'/);
assert.match(read('hooks/useAsyncAction.ts'), /Saved successfully/);
assert.match(read('lib/sqliteJson.ts'), /CryptoKey/);
assert.match(read('lib/sqliteStore.ts'), /verifyMigratedEntries/);
assert.match(read('lib/localStore.ts'), /Capacitor\.getPlatform\(\)\s*!==\s*['"]android['"]/);
assert.match(read('lib/sqliteStore.ts'), /androidIsEncryption|setEncryptionSecret|createConnection\(DATABASE_NAME, true, 'secret'/);
assert.match(read('admin/adminBackup.ts'), /saveWorkspaceBackupFile/);
assert.match(read('admin/adminBackup.ts'), /truck_customers/);
const adminFunctionSource = readBackend('supabase/functions/system-admin/index.ts');
assert.match(adminFunctionSource, /truck_customers/);
assert.match(adminFunctionSource, /customer_id,occurred_on,transaction_type/);
assert.match(adminFunctionSource, /counterparty_type,counterparty_name,settles_transaction_id/);
const truckRestoreMigration = readBackend('supabase/migrations/202608260002_complete_truck_backup_restore.sql');
assert.match(truckRestoreMigration, /target_backup->'truck_customers'/);
assert.match(truckRestoreMigration, /transaction_map/);
assert.match(readBackend('supabase/functions/lifecycle/index.ts'), /'truck_customers'/);
assert.doesNotMatch(read('admin/adminBackup.ts'), /saveBinaryFile/);
assert.match(read('components/SettingsPage.tsx'), /SyncSettingsCard/);
assert.match(read('components/SettingsPage.tsx'), /mathan:sync-progress/);
assert.match(read('components/AppToast.tsx'), /syncNotificationsEnabled/);
assert.match(read('auth/AuthGate.tsx'), /if \(!navigator\.onLine\)/);
assert.match(read('auth/AuthGate.tsx'), /3500/);
assert.match(read('apps/truck/components/Pages/CustomersPage.tsx'), /balance\.net > 0 \? 'RECEIVABLE'/);
assert.doesNotMatch(read('apps/truck/components/Pages/CustomersPage.tsx'), /Receivable: <strong/);
assert.doesNotMatch(read('apps/truck/components/Pages/CustomersPage.tsx'), /window\.confirm/);
assert.match(read('lib/localStore.ts'), /export interface OfflineStore/);
assert.doesNotMatch(read('auth/guestWorkspaces.ts'), /\b(readOffline|writeOffline|deleteOffline)\b/);
assert.doesNotMatch(read('admin/adminBackup.ts'), /\b(readOffline|writeOffline|deleteOffline)\b/);
assert.match(read('auth/AuthProvider.tsx'), /offlineStore\.read/);
assert.match(read('auth/AuthProvider.tsx'), /offlineStore\.write/);
assert.match(read('lib/repositories/snapshotRepository.ts'), /offlineStore/);
assert.match(read('lib/syncQueue.ts'), /offlineStore/);
assert.match(read('lib/syncQueue.ts'), /mergeQueuedMutation/);
assert.match(read('lib/syncQueue.ts'), /writeAtomic\(\[\.\.\.records, \{ key: KEY, value: nextQueue \}\]\)/);
assert.match(read('lib/offlineSync.ts'), /replaceQueue\(remaining, ordered\.map/);
assert.match(read('apps/truck/App.tsx'), /from ['"]\.\.\/\.\.\/components\/DeleteConfirmModal/);
assert.doesNotMatch(read('apps/truck/App.tsx'), /components\/ConfirmDeleteModal/);
assert.match(read('apps/book/cashBookRepository.ts'), /export function createBook/);
assert.match(read('apps/book/cashBookRepository.ts'), /export async function saveNewBook/);
assert.match(read('apps/payroll/payrollRepository.ts'), /export function addEmployee/);
assert.match(read('apps/payroll/payrollRepository.ts'), /export async function saveEmployee/);
assert.match(read('apps/truck/truckRepository.ts'), /withCacheLock/);
assert.match(read('apps/truck/truckRepository.ts'), /persistTruckChange/);
assert.match(read('apps/truck/truckRepository.ts'), /enqueueMutationsAtomic/);
assert.doesNotMatch(read('apps/truck/truckRepository.ts'), /queueRow\(/);
assert.match(read('apps/truck/truckRepository.ts'), /\[\{ key: storageKey, value: next \}\]/);
assert.match(read('apps/truck/truckRepository.ts'), /synchronizeTruckData/);
assert.doesNotMatch(read('apps/truck/useTruckData.ts'), /syncQueue|refreshTruckDataFromCloud/);
assert.doesNotMatch(read('apps/truck/truckRepository.ts'), /supabase\.from\('(trucks|truck_owners|truck_transactions)'\)\.(insert|update)/);
assert.doesNotMatch(read('apps/truck/truckRepository.ts'), /supabase\.from\('truck_transactions'\)\.insert/);
assert.match(read('apps/truck/useTruckData.ts'), /synchronizeTruckData/);
assert.doesNotMatch(read('apps/truck/App.tsx'), /from ['"]\.\/truckRepository/);
assert.match(read('apps/truck/useTruckMutations.ts'), /createTruckTransactionBatch/);
assert.doesNotMatch(read('apps/truck/useTruckMutations.ts'), /supabase|localStore|offlineStore/);
assert.doesNotMatch(read('apps/book/App.tsx'), /setBooks/);
assert.doesNotMatch(read('apps/book/App.tsx'), /showAppToast/);
assert.doesNotMatch(read('apps/payroll/App.tsx'), /setEmployees/);
assert.match(read('apps/book/App.tsx'), /cashBookRepository/);
assert.match(read('apps/book/App.tsx'), /CashBookViewContent/);
assert.doesNotMatch(read('apps/book/App.tsx'), /<DashboardView|<BookDetailView/);
assert.match(read('apps/book/components/CashBookViewContent.tsx'), /activeBook/);
assert.match(read('apps/payroll/App.tsx'), /payrollRepository/);
assert.match(read('apps/book/cashBookRepository.ts'), /useSnapshotRepository/);
assert.match(read('apps/book/cashBookRepository.ts'), /updateBooks/);
assert.match(read('apps/book/cashBookRepository.ts'), /updateTransactions/);
assert.match(read('apps/payroll/payrollRepository.ts'), /useSnapshotRepository/);
assert.match(read('apps/payroll/payrollRepository.ts'), /updateEmployees/);
assert.match(read('apps/payroll/payrollRepository.ts'), /updateTransactions/);
assert.match(read('apps/payroll/App.tsx'), /PayrollViewContent/);
assert.doesNotMatch(read('apps/payroll/App.tsx'), /<DashboardView|<AddEmployeeView|<PaySalaryView|<AddRaiseView|<ReportsView|<TransactionsView|<ManageEmployeesView/);
assert.match(read('apps/payroll/components/PayrollViewContent.tsx'), /activeTab === 'dashboard'/);
assert.match(read('apps/book/cashBookStore.ts'), /Compatibility entry point/);
assert.match(read('apps/payroll/payrollStore.ts'), /Compatibility entry point/);
assert.match(read('apps/truck/components/Pages/CashReportView.tsx'), /DeleteConfirmModal/);
assert.match(read('apps/truck/components/Pages/PartnersPage.tsx'), /OwnerCard/);
assert.doesNotMatch(read('apps/truck/App.tsx'), /<OwnerCard/);
assert.match(read('apps/payroll/components/EmployeeDetailModal.tsx'), /useAsyncAction/);
assert.match(read('apps/payroll/components/EmployeeDetailModal.tsx'), /submitting/);
assert.match(read('apps/book/components/BookDetailView.tsx'), /await onDeleteTransaction/);
assert.match(read('apps/truck/useTruckFinancials.ts'), /calculateTruckFinancials/);
assert.match(read('apps/truck/useTruckPreferences.ts'), /mathan_truck_preferences_/);

const gate = createActionGate();
let releaseFirst: (() => void) | undefined;
const first = gate.run(() => new Promise<string>((resolve) => { releaseFirst = () => resolve('first'); }));
const duplicate = await gate.run(async () => 'duplicate');
assert.equal(duplicate, undefined, 'rapid duplicate actions must be ignored while the first action is active');
releaseFirst?.();
assert.equal(await first, 'first');
assert.equal(gate.isActive(), false, 'action gate must release after completion');

const snapshotSource = read('lib/repositories/snapshotRepository.ts');
assert.match(snapshotSource, /enqueueMutationsAtomic/);
assert.match(snapshotSource, /\[\{ key: context\.storageKey, value \}\]/);
assert.ok(snapshotSource.indexOf('relevant.length > 0') < snapshotSource.indexOf('await offlineStore.write(context.storageKey, remote.payload)'), 'pending local snapshots must be protected from cloud hydration');
assert.match(snapshotSource, /Hydration must never wait for a network flush/);
const snapshotHookSource = read('lib/repositories/useSnapshotRepository.ts');
assert.ok(snapshotHookSource.indexOf('await persistSnapshot(context, nextValue') < snapshotHookSource.indexOf('setValue(nextValue)'), 'snapshot state must update after durable persistence');
const prefetchSource = read('lib/offlinePrefetch.ts');
assert.match(prefetchSource, /withSnapshotStorageLock/);
assert.match(prefetchSource, /mutation\.table === 'app_state_snapshots'/);
assert.match(prefetchSource, /shouldApplyRemoteSnapshot\(row\.revision, localRevision, pending\)/);
const localStoreSource = read('lib/localStore.ts');
assert.ok(localStoreSource.indexOf('await isNativeMigrationComplete()') < localStoreSource.indexOf('readLegacyStore(STORE_NAME)'), 'completed SQLite migrations must bypass the legacy IndexedDB scan');
assert.doesNotMatch(read('hooks/useAndroidBackButton.ts'), /window\.confirm/);
assert.match(read('App.tsx'), /Exit Mathan ERP\?/);
assert.doesNotMatch(read('components/AppToast.tsx'), /status === 'syncing'/);
assert.match(read('apps/book/components/AddBookModal.tsx'), /useAsyncAction/);
assert.match(read('apps/book/components/AddBookModal.tsx'), /runAction/);
assert.match(read('apps/book/components/ImportBookModal.tsx'), /useAsyncAction/);
assert.match(read('apps/book/components/ImportBookModal.tsx'), /runAction/);
assert.match(read('apps/book/components/RenameBookModal.tsx'), /runAction/);
assert.match(read('apps/book/components/AddMembersModal.tsx'), /useAsyncAction/);
assert.match(read('apps/payroll/views/PaySalaryView.tsx'), /useAsyncAction/);
assert.match(read('apps/payroll/views/PaySalaryView.tsx'), /runAction/);
assert.match(read('apps/payroll/views/AddEmployeeView.tsx'), /runAction/);
assert.match(read('apps/payroll/views/ManageEmployeesView.tsx'), /runAction/);
assert.match(read('apps/payroll/components/EmployeeDetailModal.tsx'), /runAction/);
assert.match(read('apps/truck/components/AddPartnerModal.tsx'), /useAsyncAction/);
assert.match(read('apps/truck/components/AddPartnerModal.tsx'), /runAction/);
assert.match(read('apps/truck/components/Modals/AddOwnerModal.tsx'), /runAction/);
assert.match(read('apps/truck/components/Modals/AddTruckModal.tsx'), /runAction/);
assert.match(read('apps/truck/components/Pages/AddOwnerPage.tsx'), /runAction/);
assert.match(read('apps/truck/components/Pages/ExpensesPage.tsx'), /runAction/);
assert.match(read('apps/truck/components/Pages/IncomePage.tsx'), /runAction/);
assert.match(read('apps/truck/components/Pages/ManageTrucksPage.tsx'), /runAction/);
assert.match(read('apps/truck/components/Pages/RecordTransactionPage.tsx'), /useTruckTransactionForm/);
assert.match(read('apps/truck/components/Modals/RecordTransactionModal.tsx'), /useTruckTransactionForm/);
assert.match(read('apps/truck/components/useTruckTransactionForm.ts'), /runAction/);
assert.match(read('apps/truck/components/Modals/RecordTransactionModal.tsx'), /TransactionTypeTabs/);
assert.match(read('apps/truck/components/Pages/RecordTransactionPage.tsx'), /TransactionTypeTabs/);
assert.match(read('apps/truck/components/Modals/AddOwnerModal.tsx'), /OwnerFormFields/);
assert.match(read('apps/truck/components/Pages/AddOwnerPage.tsx'), /OwnerFormFields/);
assert.match(read('apps/truck/components/AddPartnerModal.tsx'), /useOwnerFormDraft/);
assert.match(read('apps/truck/components/Modals/AddOwnerModal.tsx'), /useOwnerFormDraft/);
assert.match(read('apps/truck/components/Pages/AddOwnerPage.tsx'), /useOwnerFormDraft/);
assert.match(read('apps/truck/components/Modals/AddTruckModal.tsx'), /TruckFormFields/);
assert.match(read('apps/truck/components/Pages/ManageTrucksPage.tsx'), /TruckFormFields/);
assert.match(read('apps/truck/components/TruckFormFields.tsx'), /vin/);
for (const obsolete of [
  'apps/payroll/components/AddEmployeeModal.tsx',
  'apps/payroll/components/AddRaiseModal.tsx',
  'apps/payroll/components/RecordWithdrawalModal.tsx',
  'apps/truck/components/Modals/DistributeProfitModal.tsx',
  'apps/truck/components/Modals/PayOwnerModal.tsx',
  'apps/truck/components/Pages/PayOwnerPage.tsx',
  'apps/truck/components/Pages/DistributeProfitPage.tsx',
]) assert.equal(fs.existsSync(path.join(sourceRoot, obsolete)), false, `${obsolete} must not return as an unguarded duplicate form`);

console.log('Architecture boundary tests passed.');
