import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createActionGate } from '../src/hooks/useAsyncAction';

const sourceRoot = path.resolve('src');
const read = (relativePath: string) => fs.readFileSync(path.join(sourceRoot, relativePath), 'utf8');
const readBackend = (relativePath: string) => fs.readFileSync(path.resolve('../backend', relativePath), 'utf8');
const readMobile = (relativePath: string) => fs.readFileSync(path.resolve('../mobile', relativePath), 'utf8');
const collectTsx = (directory: string): string[] => fs.readdirSync(path.join(sourceRoot, directory), { withFileTypes: true }).flatMap((entry) => entry.isDirectory() ? collectTsx(path.join(directory, entry.name)) : entry.name.endsWith('.tsx') ? [path.join(directory, entry.name)] : []);

const appFiles = ['apps/book/App.tsx', 'apps/payroll/App.tsx', 'apps/truck/App.tsx'].map(read).join('\n');
assert.doesNotMatch(appFiles, /PersistenceToast|usePersistenceStatus|useCloudSnapshot/);
assert.doesNotMatch(appFiles, /supabase|localStore|offlineStore|app_state_snapshots|syncQueue/);
assert.doesNotMatch([read('auth/AuthGate.tsx'), ...collectTsx('components').map(read)].join('\n'), /supabase/);
assert.doesNotMatch([...collectTsx('apps').map(read), read('lib/repositories/types.ts')].join('\n'), /Your entries were kept|Your entry was kept/);
assert.match(read('lib/repositories/useSnapshotRepository.ts'), /persistSnapshot/);
assert.match(read('lib/repositories/mutationLifecycle.ts'), /persistBeforeQueue/);
assert.match(read('components/AppToast.tsx'), /mathan:toast/);
assert.match(read('components/AppToast.tsx'), /lastKey/);
assert.match(read('components/AppToast.tsx'), /recentPersistence/);
assert.match(read('components/AppToast.tsx'), /mathan:sync-status/);
assert.match(read('components/AppToast.tsx'), /mathan:sync-conflict/);
assert.doesNotMatch(read('components/AppNotificationCenter.tsx'), /mathan:sync-status|mathan:sync-conflict/);
assert.doesNotMatch(read('lib/offlineSync.ts'), /mathan:truck-storage-status/);
assert.doesNotMatch(read('apps/truck/truckRepository.ts'), /mathan:truck-storage-status/);
assert.match(read('components/AppToast.tsx'), /toast\.tone/);
assert.match(read('lib/toast.ts'), /emitSyncStatus/);
assert.match(read('lib/toast.ts'), /emitSyncConflict/);
assert.doesNotMatch(read('lib/mobile.ts'), /@capacitor\/toast/);
assert.doesNotMatch(read('lib/mobile.ts'), /showAppToast|emitToast/);
assert.doesNotMatch(read('lib/offlineSync.ts'), /window\.dispatchEvent\(new CustomEvent/);
assert.doesNotMatch(read('lib/repositories/snapshotRepository.ts'), /window\.dispatchEvent\(new CustomEvent/);
assert.doesNotMatch(read('lib/repositories/useSnapshotRepository.ts'), /window\.dispatchEvent\(new CustomEvent/);
assert.match(read('components/DeleteConfirmModal.tsx'), /successMessage/);
assert.match(read('components/DeleteConfirmModal.tsx'), /tone: 'error'/);
assert.match(read('components/DeleteConfirmModal.tsx'), /Action completed successfully/);
assert.match(read('hooks/useDeleteConfirmation.ts'), /close only after the operation succeeds/);
assert.match(read('hooks/useDeleteConfirmation.ts'), /await request\.onConfirm/);
assert.match(read('apps/truck/useTruckMutations.ts'), /DeleteConfirmationRequest/);
assert.match(read('apps/book/components/DeleteBookModal.tsx'), /successMessage/);
assert.match(read('apps/truck/App.tsx'), /useDeleteConfirmation/);
assert.match(read('apps/truck/App.tsx'), /TruckViewContent/);
assert.doesNotMatch(read('apps/truck/App.tsx'), /<DashboardView|<ExpensesPage|<ManageTrucksPage|<ExportPage/);
assert.match(read('apps/truck/components/TruckViewContent.tsx'), /currentView === 'dashboard'/);
assert.match(read('components/AppConnectivityBanner.tsx'), /useOnlineStatus/);
assert.match(read('components/AppConnectivityBanner.tsx'), /Offline/);
assert.match(read('components/AppConnectivityBanner.tsx'), /fixed bottom-20/);
assert.match(read('index.css'), /admin-sidebar \{ width: 240px !important/);
assert.match(read('lib/fileExport.ts'), /createCsv/);
assert.match(read('components/ExportButton.tsx'), /bg-\[#3f4d34\]/);
assert.match(read('components/ExportDialog.tsx'), /Export report/);
assert.match(read('components/ExportDialog.tsx'), /<AppSelect/);
assert.match(read('components/ExportDialog.tsx'), /Preview/);
assert.match(read('lib/exports/datePresets.ts'), /weekly/);
assert.match(read('lib/exports/exportMetadata.ts'), /Company/);
assert.match(read('lib/exports/pdfExporter.ts'), /report.headers/);
assert.match(read('apps/book/cashBookExport.ts'), /Opening balance/);
assert.match(read('apps/book/cashBookExport.ts'), /Final balance/);
assert.match(read('lib/exports/dateFormatting.ts'), /formatExportDate/);
assert.match(read('lib/mobile.ts'), /const columnWidth = width \/ labels.length/);
assert.doesNotMatch(read('lib/mobile.ts'), /includes\('transaction'\)/);
assert.match(read('apps/book/App.tsx'), /buildCashBookExportReports/);
assert.match(read('apps/payroll/App.tsx'), /buildPayrollExportReports/);
assert.equal(fs.existsSync(path.join(sourceRoot, 'apps/truck/components/Pages/ExportPage.tsx')), false);
assert.equal(fs.existsSync(path.join(sourceRoot, 'apps/truck/components/Modals/ExportModal.tsx')), false);
assert.equal(fs.existsSync(path.join(sourceRoot, 'apps/payroll/components/PayrollReportModal.tsx')), false);
assert.equal(fs.existsSync(path.join(sourceRoot, 'apps/payroll/components/TransactionsList.tsx')), false);
assert.match(read('lib/exports/exportService.ts'), /exportReport/);
assert.match(read('lib/exports/exportTypes.ts'), /ExportContext/);
assert.match(read('components/ExportDialog.tsx'), /context\.reportName/);
assert.doesNotMatch(read('apps/book/components/Header.tsx'), /ExportButton/);
assert.doesNotMatch(read('apps/payroll/components/TopNavbar.tsx'), /ExportButton/);
assert.doesNotMatch(read('apps/truck/components/TopHeader.tsx'), /ExportButton/);
assert.doesNotMatch(read('apps/payroll/components/Header.tsx'), /Export Payroll|ExportButton|onOpenExportModal/);
assert.match(read('apps/book/components/BookDetailView.tsx'), /ExportButton/);
assert.match(read('apps/book/components/BookDetailView.tsx'), /OPENING BALANCE/);
assert.match(read('apps/book/components/BookDetailView.tsx'), /book\.openingBalance \?\? 0/);
assert.match(read('apps/book/components/BookDetailView.tsx'), /NET BALANCE/);
assert.match(read('apps/payroll/views/ReportsView.tsx'), /ExportButton/);
assert.match(read('apps/payroll/views/TransactionsView.tsx'), /ExportButton/);
assert.match(read('apps/truck/components/Pages/CashReportView.tsx'), /ExportButton/);
assert.match(read('apps/truck/components/ReportsView.tsx'), /ExportButton/);
assert.match(read('apps/truck/components/LedgerHistoryView.tsx'), /ExportButton/);
assert.match(read('components/CompanySelector.tsx'), /useAsyncAction/);
assert.match(read('lib/repositories/snapshotRepository.ts'), /snapshotTails/);
assert.match(read('lib/repositories/snapshotRepository.ts'), /relevant\.length > 0/);
assert.match(read('lib/repositories/personalDataRepository.ts'), /loadPersonalDataArchive/);
assert.match(read('components/SettingsPage.tsx'), /loadPersonalDataArchive/);
assert.doesNotMatch(read('components/SettingsPage.tsx'), /supabase\.from\('(app_state_snapshots|trucks|truck_owners|truck_transactions)'\)/);
assert.doesNotMatch(read('components/CompanySelector.tsx'), /window\.confirm/);
assert.doesNotMatch(read('components/SettingsPage.tsx'), /window\.confirm/);
assert.match(read('hooks/useAsyncAction.ts'), /gate\.current/);
assert.match(read('hooks/useAsyncAction.ts'), /runAction/);
assert.match(read('hooks/useAsyncAction.ts'), /tone: 'success'/);
assert.match(read('hooks/useAsyncAction.ts'), /tone: 'error'/);
assert.match(read('hooks/useAsyncAction.ts'), /Saved successfully/);
assert.match(read('lib/sqliteJson.ts'), /CryptoKey/);
assert.match(read('lib/sqliteStore.ts'), /verifyMigratedEntries/);
assert.match(read('lib/localStore.ts'), /Capacitor\.getPlatform\(\)\s*!==\s*['"]android['"]/);
assert.match(read('lib/sqliteStore.ts'), /androidIsEncryption|setEncryptionSecret|createConnection\(DATABASE_NAME, true, 'secret'/);
assert.match(read('lib/cacheRepair.ts'), /recordCacheRepair/);
assert.match(read('lib/repositories/snapshotRepository.ts'), /cache-only/);
assert.match(read('apps/truck/truckRepository.ts'), /relational write is already authoritative/);
assert.match(readMobile('capacitor.config.ts'), /androidIsEncryption:\s*true/);
const fileSaverSource = fs.readFileSync(path.resolve('../mobile/android/app/src/main/java/com/mathan/erp/FileSaverPlugin.java'), 'utf8');
assert.match(fileSaverSource, /saveToAppMediaBackups/);
assert.match(fileSaverSource, /getExternalMediaDirs\(\)/);
assert.match(fileSaverSource, /new File\(mediaDirectories\[0\], "backups"\)/);
const androidManifest = fs.readFileSync(path.resolve('../mobile/android/app/src/main/AndroidManifest.xml'), 'utf8');
assert.doesNotMatch(androidManifest, /WRITE_EXTERNAL_STORAGE|MANAGE_EXTERNAL_STORAGE/);
assert.match(androidManifest, /android:allowBackup="false"/);
assert.match(read('admin/adminBackup.ts'), /saveWorkspaceBackupFile/);
assert.match(read('admin/adminBackup.ts'), /function localDayKey/);
assert.doesNotMatch(read('admin/adminBackup.ts'), /toISOString\(\)\.slice\(0, 10\)/);
assert.match(read('admin/adminBackup.ts'), /truck_customers/);
const adminFunctionSource = readBackend('supabase/functions/system-admin/index.ts');
assert.match(adminFunctionSource, /truck_customers/);
assert.match(adminFunctionSource, /customer_id,occurred_on,transaction_type/);
assert.match(adminFunctionSource, /counterparty_type,counterparty_name,settles_transaction_id/);
const truckRestoreMigration = readBackend('supabase/migrations/202608260002_complete_truck_backup_restore.sql');
assert.match(truckRestoreMigration, /target_backup->'truck_customers'/);
assert.match(truckRestoreMigration, /transaction_map/);
const ownershipTransferMigration = readBackend('supabase/migrations/202608260005_safe_workspace_ownership_transfer.sql');
assert.match(ownershipTransferMigration, /transfer_workspace_ownership/);
assert.match(ownershipTransferMigration, /'book', 'edit'/);
assert.match(ownershipTransferMigration, /'payroll', 'edit'/);
assert.match(ownershipTransferMigration, /'truck', 'edit'/);
assert.match(ownershipTransferMigration, /for update/);
assert.doesNotMatch(ownershipTransferMigration, /delete from public\.(cash|payroll|truck|app_state)/);
assert.match(readBackend('supabase/functions/lifecycle/index.ts'), /'truck_customers'/);
assert.doesNotMatch(read('admin/adminBackup.ts'), /saveBinaryFile/);
assert.match(read('components/SettingsPage.tsx'), /SyncSettingsCard/);
assert.match(read('components/SettingsPage.tsx'), /syncWorkspaceQueues\(workspace\.id\)/);
assert.match(read('components/SettingsPage.tsx'), /Ownership cannot be transferred until all offline changes finish syncing/);
assert.match(read('components/SettingsPage.tsx'), /mathan:sync-progress/);
assert.match(read('components/AppToast.tsx'), /syncNotificationsEnabled/);
assert.match(read('auth/AuthGate.tsx'), /if \(!navigator\.onLine\)/);
assert.match(read('auth/AuthGate.tsx'), /3500/);
assert.match(read('apps/truck/components/Pages/CustomersPage.tsx'), /balance\.net > 0 \? 'RECEIVABLE'/);
assert.doesNotMatch(read('apps/truck/components/Pages/CustomersPage.tsx'), /Receivable: <strong/);
assert.doesNotMatch(read('apps/truck/components/Pages/CustomersPage.tsx'), /window\.confirm/);
assert.match(read('lib/localStore.ts'), /export interface OfflineStore/);
assert.doesNotMatch(read('auth/guestWorkspaces.ts'), /\b(readOffline|writeOffline|deleteOffline)\b/);
assert.doesNotMatch(read('admin/adminBackup.ts'), /\b(readOffline|writeOffline|deleteOffline)\b/);
assert.match(read('auth/AuthProvider.tsx'), /offlineStore\.read/);
assert.match(read('auth/AuthProvider.tsx'), /offlineStore\.write/);
const workspaceCacheSource = read('auth/AuthProvider.tsx').slice(read('auth/AuthProvider.tsx').indexOf('async function readWorkspaceCache'));
assert.ok(workspaceCacheSource.indexOf('localStorage.getItem(workspaceCacheKey') < workspaceCacheSource.indexOf('offlineStore.read<OfflineWorkspaceCache>'), 'legacy workspace cache must be checked before waiting on durable storage');
assert.match(read('lib/repositories/snapshotRepository.ts'), /offlineStore/);
assert.match(read('lib/syncQueue.ts'), /offlineStore/);
assert.match(read('lib/syncQueue.ts'), /mergeQueuedMutation/);
assert.match(read('lib/syncQueue.ts'), /writeAtomic\(\[\.\.\.records, \{ key: KEY, value: nextQueue \}\]\)/);
assert.match(read('lib/syncQueue.ts'), /emitSyncProgress/);
assert.equal(fs.existsSync(path.join(sourceRoot, 'components/EntitySyncBadge.tsx')), true, 'record-level sync badge component must exist');
assert.match(read('components/EntitySyncBadge.tsx'), /useEntitySyncStatus/);
assert.match(read('components/EntitySyncBadge.tsx'), /Pending/);
assert.match(read('components/EntitySyncBadge.tsx'), /Needs attention/);
assert.match(read('lib/offlineDiagnostics.ts'), /layer: 'confirmed' \| 'effective'/);
assert.match(read('lib/offlineDiagnostics.ts'), /pendingWithoutEffective/);
assert.match(read('lib/durablePersistence.ts'), /enqueueMutationsAtomic/);
assert.match(read('lib/offlineSync.ts'), /replaceQueue\(remaining, ordered\.map/);
assert.match(read('apps/truck/App.tsx'), /from ['"]\.\.\/\.\.\/components\/DeleteConfirmModal/);
assert.doesNotMatch(read('apps/truck/App.tsx'), /components\/ConfirmDeleteModal/);
assert.match(read('apps/book/cashBookRepository.ts'), /export function createBook/);
assert.match(read('apps/book/cashBookRepository.ts'), /export async function saveNewBook/);
assert.match(read('apps/payroll/payrollRepository.ts'), /export function addEmployee/);
assert.match(read('apps/payroll/payrollRepository.ts'), /export async function saveEmployee/);
assert.match(read('apps/truck/truckRepository.ts'), /withCacheLock/);
assert.match(read('apps/truck/truckRepository.ts'), /persistTruckChange/);
assert.match(read('apps/truck/truckRepository.ts'), /saveOfflineFallback/);
const truckPendingBranch = read('apps/truck/truckRepository.ts').match(/if \(remainingStatus\) \{([\s\S]*?)\n\s*\}/)?.[1] ?? '';
assert.match(truckPendingBranch, /saveOfflineFallback/, 'a Truck save made while an older mutation is unresolved must atomically persist its effective cache and outbox row');
assert.match(read('apps/truck/truckRepository.ts'), /applyConfirmedTruckRows/);
assert.match(read('lib/offlineSync.ts'), /\.select\(\)\.single\(\)/, 'online Truck writes must cache Supabase-confirmed rows');
assert.match(read('lib/offlineSync.ts'), /expectedUpdatedAt/);
assert.match(read('lib/offlineSync.ts'), /last_mutation_id/);
assert.match(read('lib/offlineSync.ts'), /mutation\.mutationId/);
assert.match(read('lib/offlineSync.ts'), /code === 'CONFLICT'/);
assert.doesNotMatch(read('apps/truck/truckRepository.ts'), /queueRow\(/);
assert.match(read('apps/truck/truckRepository.ts'), /\[\{ key: storageKey, value: next \}\]/);
assert.match(read('apps/truck/truckRepository.ts'), /synchronizeTruckData/);
const truckSynchronizeBody = read('apps/truck/truckRepository.ts').match(/export async function synchronizeTruckData[\s\S]*?\n\}/)?.[0] ?? '';
assert.ok(truckSynchronizeBody.indexOf('refreshTruckDataFromCloud') < truckSynchronizeBody.indexOf('syncQueue'), 'Truck reconnect must fetch and overlay server state before sending pending rows');
assert.match(read('apps/truck/truckRepository.ts'), /truck:confirmed:/, 'Truck must keep confirmed server state separate from its effective cache');
assert.match(read('lib/repositories/snapshotRepository.ts'), /saveOfflineFallback/);
assert.match(read('lib/repositories/snapshotRepository.ts'), /:confirmed/, 'snapshot repositories must retain a separate confirmed baseline');
assert.match(read('lib/repositories/snapshotRepository.ts'), /threeWayMergeSnapshot/, 'new snapshot mutations must merge pending local entities over newer server state');
assert.match(read('lib/repositories/snapshotRepository.ts'), /affected_client_ids/, 'snapshot outbox rows must identify records for pending UI state');
assert.doesNotMatch(read('apps/truck/useTruckData.ts'), /syncQueue|refreshTruckDataFromCloud/);
assert.doesNotMatch(read('apps/truck/truckRepository.ts'), /supabase\.from\('(trucks|truck_owners|truck_transactions)'\)\.(insert|update)/);
assert.doesNotMatch(read('apps/truck/truckRepository.ts'), /supabase\.from\('truck_transactions'\)\.insert/);
assert.match(read('apps/truck/useTruckData.ts'), /synchronizeTruckData/);
assert.doesNotMatch(read('apps/truck/App.tsx'), /from ['"]\.\/truckRepository/);
assert.match(read('apps/truck/useTruckMutations.ts'), /createTruckTransactionBatch/);
assert.doesNotMatch(read('apps/truck/useTruckMutations.ts'), /supabase|localStore|offlineStore/);
assert.doesNotMatch(read('apps/book/App.tsx'), /setBooks/);
assert.doesNotMatch(read('apps/book/App.tsx'), /showAppToast/);
assert.doesNotMatch(read('apps/payroll/App.tsx'), /setEmployees/);
assert.match(read('apps/book/App.tsx'), /cashBookRepository/);
assert.match(read('apps/book/App.tsx'), /CashBookViewContent/);
assert.doesNotMatch(read('apps/book/App.tsx'), /<DashboardView|<BookDetailView/);
assert.match(read('apps/book/components/CashBookViewContent.tsx'), /activeBook/);
assert.match(read('apps/payroll/App.tsx'), /payrollRepository/);
assert.match(read('apps/book/cashBookRepository.ts'), /useSnapshotRepository/);
assert.match(read('apps/book/cashBookRepository.ts'), /updateBooks/);
assert.match(read('apps/book/cashBookRepository.ts'), /updateTransactions/);
assert.match(read('apps/payroll/payrollRepository.ts'), /useSnapshotRepository/);
assert.match(read('apps/payroll/payrollRepository.ts'), /updateEmployees/);
assert.match(read('apps/payroll/payrollRepository.ts'), /updateTransactions/);
assert.match(read('apps/payroll/views/AddEmployeeView.tsx'), /crypto\.randomUUID\(\)/, 'offline employees must use permanent UUIDs');
assert.match(read('apps/payroll/views/ManageEmployeesView.tsx'), /crypto\.randomUUID\(\)/, 'offline salary changes must use permanent UUIDs');
assert.match(read('apps/payroll/views/AddRaiseView.tsx'), /crypto\.randomUUID\(\)/, 'offline raises must use permanent UUIDs');
assert.match(read('apps/payroll/views/PaySalaryView.tsx'), /crypto\.randomUUID\(\)/, 'offline payroll payments must use permanent UUIDs');
assert.doesNotMatch(read('apps/payroll/views/AddEmployeeView.tsx'), /Date\.now\(\).*id/);
assert.doesNotMatch(read('apps/payroll/views/ManageEmployeesView.tsx'), /Date\.now\(\).*id/);
assert.doesNotMatch(read('apps/payroll/views/AddRaiseView.tsx'), /Date\.now\(\).*id/);
assert.doesNotMatch(read('apps/payroll/views/PaySalaryView.tsx'), /Date\.now\(\).*id/);
assert.match(read('apps/payroll/App.tsx'), /PayrollViewContent/);
assert.doesNotMatch(read('apps/payroll/App.tsx'), /<DashboardView|<AddEmployeeView|<PaySalaryView|<AddRaiseView|<ReportsView|<TransactionsView|<ManageEmployeesView/);
assert.match(read('apps/payroll/components/PayrollViewContent.tsx'), /activeTab === 'dashboard'/);
assert.match(read('apps/book/cashBookStore.ts'), /Compatibility entry point/);
assert.match(read('apps/payroll/payrollStore.ts'), /Compatibility entry point/);
assert.match(read('apps/truck/components/Pages/CashReportView.tsx'), /DeleteConfirmModal/);
assert.match(read('apps/truck/components/Pages/PartnersPage.tsx'), /OwnerCard/);
assert.doesNotMatch(read('apps/truck/App.tsx'), /<OwnerCard/);
assert.match(read('apps/payroll/components/EmployeeDetailModal.tsx'), /useAsyncAction/);
assert.match(read('apps/payroll/components/EmployeeDetailModal.tsx'), /submitting/);
assert.match(read('apps/book/components/BookDetailView.tsx'), /await onDeleteTransaction/);
assert.match(read('apps/truck/useTruckFinancials.ts'), /calculateTruckFinancials/);
assert.match(read('apps/truck/useTruckPreferences.ts'), /mathan_truck_preferences_/);

const gate = createActionGate();
let releaseFirst: (() => void) | undefined;
const first = gate.run(() => new Promise<string>((resolve) => { releaseFirst = () => resolve('first'); }));
const duplicate = await gate.run(async () => 'duplicate');
assert.equal(duplicate, undefined, 'rapid duplicate actions must be ignored while the first action is active');
releaseFirst?.();
assert.equal(await first, 'first');
assert.equal(gate.isActive(), false, 'action gate must release after completion');

const snapshotSource = read('lib/repositories/snapshotRepository.ts');
assert.match(snapshotSource, /saveOfflineFallback/);
assert.match(snapshotSource, /\[\{ key: context\.storageKey, value \}\]/);
const hydrateSnapshotSource = snapshotSource.slice(snapshotSource.indexOf('export async function hydrateSnapshot'));
assert.ok(hydrateSnapshotSource.indexOf('confirmedKey(context.storageKey)') < hydrateSnapshotSource.indexOf('reconcilePendingSnapshotMutation'), 'server state must enter the confirmed layer before pending local snapshots are rebased');
assert.match(snapshotSource, /Fetch the confirmed server layer first/);
const snapshotHookSource = read('lib/repositories/useSnapshotRepository.ts');
assert.ok(snapshotHookSource.indexOf('await persistSnapshot(context, nextValue') < snapshotHookSource.indexOf('setValue(nextValue)'), 'snapshot state must update after durable persistence');
const snapshotOnlineHandler = snapshotHookSource.slice(snapshotHookSource.indexOf("window.addEventListener('online'" ) - 500);
assert.doesNotMatch(snapshotOnlineHandler, /syncQueue\(/, 'snapshot online events must reconcile confirmed state before queue flush');
const prefetchSource = read('lib/offlinePrefetch.ts');
assert.match(prefetchSource, /withSnapshotStorageLock/);
assert.match(prefetchSource, /mutation\.table === 'app_state_snapshots'/);
assert.match(prefetchSource, /threeWayMergeSnapshot/);
assert.match(prefetchSource, /reconcilePendingSnapshotMutation/);
const authReconnectSource = read('auth/AuthProvider.tsx').slice(read('auth/AuthProvider.tsx').indexOf('const active = memberships.filter'));
assert.ok(authReconnectSource.indexOf('prefetchWorkspaceData') < authReconnectSource.indexOf('syncWorkspaceQueues'), 'startup reconnect must fetch confirmed state before sending pending mutations');
const localStoreSource = read('lib/localStore.ts');
assert.ok(localStoreSource.indexOf('readNativeMigrationState()') < localStoreSource.indexOf('readLegacyStore(STORE_NAME)'), 'completed SQLite migrations must bypass the legacy IndexedDB scan');
assert.match(localStoreSource, /nativeMigrationState/);
assert.match(localStoreSource, /readNativeMigrationState/);
assert.match(localStoreSource, /Android SQLite rejected the durable write/, 'Android business writes must fail visibly instead of silently splitting into IndexedDB');
assert.match(localStoreSource, /If either deletion fails, restore a fallback copy/);
const deleteSource = localStoreSource.slice(localStoreSource.indexOf('export async function deleteOffline'));
assert.ok(deleteSource.indexOf('await deleteIndexedDb(key)') < deleteSource.indexOf('removeFallback(key)'), 'delete must remove the legacy record before clearing recovery data');
assert.doesNotMatch(read('hooks/useAndroidBackButton.ts'), /window\.confirm/);
assert.match(read('App.tsx'), /Exit Mathan ERP\?/);
assert.doesNotMatch(read('components/AppToast.tsx'), /status === 'syncing'/);
assert.match(read('apps/book/components/AddBookModal.tsx'), /useAsyncAction/);
assert.match(read('apps/book/components/AddBookModal.tsx'), /runAction/);
assert.match(read('apps/book/components/ImportBookModal.tsx'), /useAsyncAction/);
assert.match(read('apps/book/components/ImportBookModal.tsx'), /runAction/);
assert.match(read('apps/book/components/RenameBookModal.tsx'), /runAction/);
assert.match(read('apps/book/components/AddMembersModal.tsx'), /useAsyncAction/);
assert.match(read('apps/payroll/views/PaySalaryView.tsx'), /useAsyncAction/);
assert.match(read('apps/payroll/views/PaySalaryView.tsx'), /runAction/);
assert.match(read('apps/payroll/views/AddEmployeeView.tsx'), /runAction/);
assert.match(read('apps/payroll/views/ManageEmployeesView.tsx'), /runAction/);
assert.match(read('apps/payroll/components/EmployeeDetailModal.tsx'), /runAction/);
assert.match(read('apps/truck/components/AddPartnerModal.tsx'), /useAsyncAction/);
assert.match(read('apps/truck/components/AddPartnerModal.tsx'), /runAction/);
assert.match(read('apps/truck/components/Modals/AddOwnerModal.tsx'), /runAction/);
assert.match(read('apps/truck/components/Modals/AddTruckModal.tsx'), /runAction/);
assert.match(read('apps/truck/components/Pages/AddOwnerPage.tsx'), /runAction/);
assert.match(read('apps/truck/components/Pages/ExpensesPage.tsx'), /runAction/);
assert.match(read('apps/truck/components/Pages/IncomePage.tsx'), /runAction/);
assert.match(read('apps/truck/components/Pages/ManageTrucksPage.tsx'), /runAction/);
assert.match(read('apps/truck/components/Pages/RecordTransactionPage.tsx'), /useTruckTransactionForm/);
assert.match(read('apps/truck/components/Modals/RecordTransactionModal.tsx'), /useTruckTransactionForm/);
assert.match(read('apps/truck/components/useTruckTransactionForm.ts'), /runAction/);
assert.match(read('apps/truck/components/Modals/RecordTransactionModal.tsx'), /TransactionTypeTabs/);
assert.match(read('apps/truck/components/Pages/RecordTransactionPage.tsx'), /TransactionTypeTabs/);
assert.match(read('apps/truck/components/Modals/AddOwnerModal.tsx'), /OwnerFormFields/);
assert.match(read('apps/truck/components/Pages/AddOwnerPage.tsx'), /OwnerFormFields/);
assert.match(read('apps/truck/components/AddPartnerModal.tsx'), /useOwnerFormDraft/);
assert.match(read('apps/truck/components/Modals/AddOwnerModal.tsx'), /useOwnerFormDraft/);
assert.match(read('apps/truck/components/Pages/AddOwnerPage.tsx'), /useOwnerFormDraft/);
assert.match(read('apps/truck/components/Modals/AddTruckModal.tsx'), /TruckFormFields/);
assert.match(read('apps/truck/components/Pages/ManageTrucksPage.tsx'), /TruckFormFields/);
assert.match(read('apps/truck/components/TruckFormFields.tsx'), /vin/);
for (const obsolete of [
  'apps/payroll/components/AddEmployeeModal.tsx',
  'apps/payroll/components/AddRaiseModal.tsx',
  'apps/payroll/components/RecordWithdrawalModal.tsx',
  'apps/truck/components/Modals/DistributeProfitModal.tsx',
  'apps/truck/components/Modals/PayOwnerModal.tsx',
  'apps/truck/components/Pages/PayOwnerPage.tsx',
  'apps/truck/components/Pages/DistributeProfitPage.tsx',
]) assert.equal(fs.existsSync(path.join(sourceRoot, obsolete)), false, `${obsolete} must not return as an unguarded duplicate form`);

console.log('Architecture boundary tests passed.');
