project_id = "mathan-erp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["mathanerp://auth/callback"]

[functions.system-admin]
verify_jwt = true
