import { supabase } from '../../lib/supabase';
import { readOffline, writeOffline } from '../../lib/localStore';
import { enqueueMutation } from '../../lib/syncQueue';
import type { Owner, Transaction, Truck } from './types';
function explain(error: { message?: string; code?: string }) { if (error.code === '42P01' || error.code === 'PGRST205' || error.message?.toLowerCase().includes('could not find the table')) return new Error('Truck tables are not installed in Supabase yet. Run the Truck migrations, then refresh the app.'); return error; }
const truckFromDb = (r: Record<string, unknown>): Truck => ({ id: String(r.id), name: String(r.name ?? ''), unitNumber: String(r.unit_number ?? ''), makeModel: String(r.make_model ?? ''), vin: String(r.vin ?? ''), cashOnHand: Number(r.cash_on_hand ?? 0), licensePlate: String(r.license_plate ?? '') });
const ownerFromDb = (r: Record<string, unknown>): Owner => ({ id: String(r.id), truckId: String(r.truck_id), name: String(r.name ?? ''), startDate: String(r.start_date ?? ''), equityPercentage: Number(r.equity_percentage ?? 0), monthlyDrawRate: Number(r.monthly_draw_rate ?? 0), avatarColor: String(r.avatar_color ?? 'bg-slate-800 text-white') });
const transactionFromDb = (r: Record<string, unknown>): Transaction => ({ id: String(r.id), truckId: String(r.truck_id), date: String(r.occurred_on), type: r.transaction_type as Transaction['type'], category: String(r.category ?? ''), amount: Number(r.amount ?? 0), ownerId: r.owner_id ? String(r.owner_id) : undefined, description: String(r.description ?? ''), referenceNo: r.reference_no ? String(r.reference_no) : undefined });
type TruckCache = { trucks: Truck[]; owners: Owner[]; transactions: Transaction[] };
const cacheKey = async (workspaceId: string) => { const { data } = await supabase.auth.getSession(); return `truck:${data.session?.user.id ?? 'guest'}:${workspaceId}`; };
const emptyCache = (): TruckCache => ({ trucks: [], owners: [], transactions: [] });
async function getCache(workspaceId: string) { return (await readOffline<TruckCache>(await cacheKey(workspaceId))) ?? emptyCache(); }
async function saveCache(workspaceId: string, value: TruckCache) { await writeOffline(await cacheKey(workspaceId), value); }
async function queueRow(table: string, workspaceId: string, payload: Record<string, unknown>) { await enqueueMutation({ table, operation: 'upsert', payload: { ...payload, workspace_id: workspaceId } }); }
export async function loadTruckData(workspaceId: string, localOnly = false) {
  const cached = await getCache(workspaceId);
  if (localOnly || !navigator.onLine) return cached;
  const [trucks, owners, transactions] = await Promise.all([supabase.from('trucks').select('*').eq('workspace_id', workspaceId).is('deleted_at', null).order('created_at'), supabase.from('truck_owners').select('*').eq('workspace_id', workspaceId).is('deleted_at', null).order('created_at'), supabase.from('truck_transactions').select('*').eq('workspace_id', workspaceId).is('deleted_at', null).order('occurred_on', { ascending: false })]);
  const error = trucks.error ?? owners.error ?? transactions.error; if (error) { if (cached.trucks.length || cached.owners.length || cached.transactions.length) return cached; throw explain(error); }
  const next = { trucks: (trucks.data ?? []).map((r) => truckFromDb(r as Record<string, unknown>)), owners: (owners.data ?? []).map((r) => ownerFromDb(r as Record<string, unknown>)), transactions: (transactions.data ?? []).map((r) => transactionFromDb(r as Record<string, unknown>)) }; await saveCache(workspaceId, next); return next;
}
export async function createTruck(workspaceId: string, v: Omit<Truck, 'id'>, localOnly = false) { const row = { id: crypto.randomUUID(), workspace_id: workspaceId, name: v.name.trim(), unit_number: v.unitNumber.trim(), make_model: v.makeModel.trim(), vin: v.vin.trim(), cash_on_hand: v.cashOnHand, license_plate: v.licensePlate.trim() }; if (localOnly || !navigator.onLine) { const cache = await getCache(workspaceId); const truck = truckFromDb(row); await saveCache(workspaceId, { ...cache, trucks: [...cache.trucks, truck] }); if (!localOnly) await queueRow('trucks', workspaceId, row); return truck; } const { data, error } = await supabase.from('trucks').insert(row).select('*').single(); if (error) throw explain(error); const truck = truckFromDb(data); const cache = await getCache(workspaceId); await saveCache(workspaceId, { ...cache, trucks: [...cache.trucks.filter((item) => item.id !== truck.id), truck] }); return truck; }
export async function createTruckOwner(workspaceId: string, v: Omit<Owner, 'id'> & { userId?: string | null }, localOnly = false) { const row = { id: crypto.randomUUID(), workspace_id: workspaceId, truck_id: v.truckId, user_id: v.userId ?? null, name: v.name, start_date: v.startDate, equity_percentage: v.equityPercentage, monthly_draw_rate: v.monthlyDrawRate, avatar_color: v.avatarColor }; if (localOnly || !navigator.onLine) { const cache = await getCache(workspaceId); const owner = ownerFromDb(row); await saveCache(workspaceId, { ...cache, owners: [...cache.owners, owner] }); if (!localOnly) await queueRow('truck_owners', workspaceId, row); return owner; } const { data, error } = await supabase.from('truck_owners').insert(row).select('*').single(); if (error) throw error; const owner = ownerFromDb(data); const cache = await getCache(workspaceId); await saveCache(workspaceId, { ...cache, owners: [...cache.owners.filter((item) => item.id !== owner.id), owner] }); return owner; }
export async function updateTruckOwner(workspaceId: string, v: Owner, localOnly = false) { const row = { id: v.id, workspace_id: workspaceId, truck_id: v.truckId, name: v.name, start_date: v.startDate, equity_percentage: v.equityPercentage, monthly_draw_rate: v.monthlyDrawRate, avatar_color: v.avatarColor, updated_at: new Date().toISOString() }; if (localOnly || !navigator.onLine) { const cache = await getCache(workspaceId); await saveCache(workspaceId, { ...cache, owners: cache.owners.map((item) => item.id === v.id ? v : item) }); if (!localOnly) await queueRow('truck_owners', workspaceId, row); return v; } const { data, error } = await supabase.from('truck_owners').update(row).eq('workspace_id', workspaceId).eq('id', v.id).select('*').single(); if (error) throw error; const owner = ownerFromDb(data); const cache = await getCache(workspaceId); await saveCache(workspaceId, { ...cache, owners: cache.owners.map((item) => item.id === owner.id ? owner : item) }); return owner; }
export async function updateTruck(workspaceId: string, v: Truck, localOnly = false) { const row = { id: v.id, workspace_id: workspaceId, name: v.name, unit_number: v.unitNumber, make_model: v.makeModel, vin: v.vin, cash_on_hand: v.cashOnHand, license_plate: v.licensePlate, updated_at: new Date().toISOString() }; if (localOnly || !navigator.onLine) { const cache = await getCache(workspaceId); await saveCache(workspaceId, { ...cache, trucks: cache.trucks.map((item) => item.id === v.id ? v : item) }); if (!localOnly) await queueRow('trucks', workspaceId, row); return v; } const { data, error } = await supabase.from('trucks').update(row).eq('workspace_id', workspaceId).eq('id', v.id).select('*').single(); if (error) throw error; const truck = truckFromDb(data); const cache = await getCache(workspaceId); await saveCache(workspaceId, { ...cache, trucks: cache.trucks.map((item) => item.id === truck.id ? truck : item) }); return truck; }
export async function deleteTruck(workspaceId: string, id: string, localOnly = false) { const deletedAt = new Date().toISOString(); const cache = await getCache(workspaceId); await saveCache(workspaceId, { ...cache, trucks: cache.trucks.filter((item) => item.id !== id) }); if (localOnly || !navigator.onLine) { if (!localOnly) await queueRow('trucks', workspaceId, { id, deleted_at: deletedAt, updated_at: deletedAt }); return; } const { error } = await supabase.from('trucks').update({ deleted_at: deletedAt, updated_at: deletedAt }).eq('workspace_id', workspaceId).eq('id', id).is('deleted_at', null); if (error) throw error; }
export async function createTruckTransaction(workspaceId: string, v: Omit<Transaction, 'id'>, localOnly = false) { const row = { id: crypto.randomUUID(), workspace_id: workspaceId, truck_id: v.truckId, owner_id: v.ownerId ?? null, occurred_on: v.date, transaction_type: v.type, category: v.category, amount: v.amount, description: v.description, reference_no: v.referenceNo ?? null }; if (localOnly || !navigator.onLine) { const cache = await getCache(workspaceId); const transaction = transactionFromDb(row); await saveCache(workspaceId, { ...cache, transactions: [...cache.transactions, transaction] }); if (!localOnly) await queueRow('truck_transactions', workspaceId, row); return transaction; } const { data, error } = await supabase.from('truck_transactions').insert(row).select('*').single(); if (error) throw error; const transaction = transactionFromDb(data); const cache = await getCache(workspaceId); await saveCache(workspaceId, { ...cache, transactions: [...cache.transactions.filter((item) => item.id !== transaction.id), transaction] }); return transaction; }
export async function updateTruckTransaction(workspaceId: string, v: Transaction, localOnly = false) { const row = { id: v.id, workspace_id: workspaceId, truck_id: v.truckId, owner_id: v.ownerId ?? null, occurred_on: v.date, transaction_type: v.type, category: v.category, amount: v.amount, description: v.description, reference_no: v.referenceNo ?? null, updated_at: new Date().toISOString() }; if (localOnly || !navigator.onLine) { const cache = await getCache(workspaceId); await saveCache(workspaceId, { ...cache, transactions: cache.transactions.map((item) => item.id === v.id ? v : item) }); if (!localOnly) await queueRow('truck_transactions', workspaceId, row); return v; } const { data, error } = await supabase.from('truck_transactions').update(row).eq('workspace_id', workspaceId).eq('id', v.id).is('deleted_at', null).select('*').single(); if (error) throw error; const transaction = transactionFromDb(data); const cache = await getCache(workspaceId); await saveCache(workspaceId, { ...cache, transactions: cache.transactions.map((item) => item.id === transaction.id ? transaction : item) }); return transaction; }
export async function softDeleteTruckTransaction(workspaceId: string, id: string, localOnly = false) { const deletedAt = new Date().toISOString(); const cache = await getCache(workspaceId); await saveCache(workspaceId, { ...cache, transactions: cache.transactions.filter((item) => item.id !== id) }); if (localOnly || !navigator.onLine) { if (!localOnly) await queueRow('truck_transactions', workspaceId, { id, deleted_at: deletedAt, updated_at: deletedAt }); return; } const { error } = await supabase.rpc('delete_truck_transaction', { target_workspace: workspaceId, target_transaction: id, approval_id: null }); if (error) throw error; }
export async function deleteTruckOwner(workspaceId: string, id: string, localOnly = false) { const deletedAt = new Date().toISOString(); const cache = await getCache(workspaceId); await saveCache(workspaceId, { ...cache, owners: cache.owners.filter((item) => item.id !== id) }); if (localOnly || !navigator.onLine) { if (!localOnly) await queueRow('truck_owners', workspaceId, { id, deleted_at: deletedAt, updated_at: deletedAt }); return; } const { error } = await supabase.from('truck_owners').update({ deleted_at: deletedAt, updated_at: deletedAt }).eq('workspace_id', workspaceId).eq('id', id); if (error) throw error; }
export async function loadTruckWorkspaceMembers(workspaceId: string) { const { data, error } = await supabase.rpc('list_workspace_members', { target_workspace: workspaceId }); if (error) throw error; return (data ?? []) as Array<{ user_id: string; email: string; display_name: string }>; }
