import type { Owner, Transaction, Truck } from './types';
import { calculateTruckFinancials, transactionDetails } from './utils/formatters';
import type { ExportBuildOptions, ExportReportDefinition } from '../../lib/exports/exportTypes';
import { formatExportNumber } from '../../lib/exports/numberFormatting';

type TruckExportData = { trucks: Truck[]; owners: Owner[]; transactions: Transaction[]; calculationDate?: string };
const money = formatExportNumber;
const inRange = (date: string, options: ExportBuildOptions) => (!options.startDate || date >= options.startDate) && (!options.endDate || date <= options.endDate);

export function buildTruckExportReports(data: TruckExportData): ExportReportDefinition[] {
  const trucks = (options: ExportBuildOptions) => data.trucks.filter((truck) => !options.entityId || truck.id === options.entityId);
  const matchesType = (tx: Transaction, type?: string) => !type || type === 'ALL' || (type === 'INFLOW' ? ['INCOME', 'CAPITAL_INJECTION', 'RECEIVABLE_SETTLEMENT'].includes(tx.type) : type === 'OUTFLOW' ? ['EXPENSE', 'CAPITAL_REPAYMENT', 'PROFIT_DISTRIBUTION', 'PAYABLE_SETTLEMENT'].includes(tx.type) : type === 'CREDIT' ? ['RECEIVABLE', 'PAYABLE'].includes(tx.type) : tx.type === type);
  const transactions = (options: ExportBuildOptions) => data.transactions.filter((tx) => { const query = options.query?.trim().toLowerCase(); const truckName = data.trucks.find((truck) => truck.id === tx.truckId)?.name ?? ''; const ownerName = data.owners.find((owner) => owner.id === tx.ownerId)?.name ?? ''; const text = `${truckName} ${ownerName} ${tx.counterpartyName ?? ''} ${tx.category} ${tx.description} ${tx.referenceNo ?? ''}`.toLowerCase(); return (!options.entityId || tx.truckId === options.entityId) && (!options.ownerId || tx.ownerId === options.ownerId) && (!options.category || tx.category === options.category) && matchesType(tx, options.transactionType) && (!query || text.includes(query)) && inRange(tx.date, options); });
  const summaries = (options: ExportBuildOptions) => trucks(options).map((truck) => { const owners = data.owners.filter((owner) => owner.truckId === truck.id); const summary = calculateTruckFinancials(truck, owners, transactions({ ...options, entityId: truck.id }), options.endDate ?? data.calculationDate); return [truck.name, truck.unitNumber, money(summary.cashOnHand), money(summary.grossIncome), money(summary.operatingExpenses), money(summary.netProfit), money(summary.totalReceivable), money(summary.totalPayable), money(summary.totalUnpaidDebtToOwners)]; });
  const financialSummary = (options: ExportBuildOptions) => trucks(options).reduce((totals, truck) => { const summary = calculateTruckFinancials(truck, data.owners.filter((owner) => owner.truckId === truck.id), transactions({ ...options, entityId: truck.id }), options.endDate ?? data.calculationDate); totals.cash += summary.cashOnHand; totals.income += summary.grossIncome; totals.expenses += summary.operatingExpenses; totals.profit += summary.netProfit; totals.receivable += summary.totalReceivable; totals.payable += summary.totalPayable; return totals; }, { cash: 0, income: 0, expenses: 0, profit: 0, receivable: 0, payable: 0 });
  const summaryItems = (options: ExportBuildOptions) => { const summary = financialSummary(options); return [{ label: 'Cash on hand', value: money(summary.cash) }, { label: 'Total income', value: money(summary.income), tone: 'positive' as const }, { label: 'Total expenses', value: money(summary.expenses), tone: 'negative' as const }, { label: 'Net profit', value: money(summary.profit) }, { label: 'Receivable', value: money(summary.receivable), tone: 'positive' as const }, { label: 'Payable', value: money(summary.payable), tone: 'negative' as const }]; };
  const transactionRows = (options: ExportBuildOptions) => { const ownerById = new Map(data.owners.map((owner) => [owner.id, owner])); return transactions(options).sort((a, b) => b.date.localeCompare(a.date)).map((tx) => [tx.date, data.trucks.find((truck) => truck.id === tx.truckId)?.name ?? '', ownerById.get(tx.ownerId ?? '')?.name ?? '', tx.counterpartyName ?? '', tx.type, tx.category, transactionDetails(tx), tx.referenceNo ?? '', money(tx.amount)]); };
  const ownerRows = (options: ExportBuildOptions) => trucks(options).flatMap((truck) => { const summary = calculateTruckFinancials(truck, data.owners.filter((owner) => owner.truckId === truck.id), transactions({ ...options, entityId: truck.id }), options.endDate ?? data.calculationDate); const query = options.query?.trim().toLowerCase(); return summary.ownerSummaries.filter((item) => (!options.ownerId || item.owner.id === options.ownerId) && (!query || item.owner.name.toLowerCase().includes(query))).map((item) => [truck.name, item.owner.name, item.owner.equityPercentage, money(item.totalInjected), money(item.totalRepaid), money(item.totalUnpaidMoneyOwed)]); });
  const report = (title: string, filename: string, headers: string[], rows: Array<Array<string | number>>, options: ExportBuildOptions, summary = summaryItems(options)) => ({ title, filename, headers, rows, summary, lines: rows.map((row) => row.join(' | ')) });
  const choose = <T,>(options: ExportBuildOptions, condensed: T, detailed: T, full: T) => options.detail === 'condensed' ? condensed : options.detail === 'detailed' ? detailed : full;
  const statement = (options: ExportBuildOptions) => choose(options,
    { title: 'Truck Summary', filename: 'truck-summary', headers: ['Truck', 'Unit', 'Cash', 'Income', 'Expenses', 'Net profit', 'Receivable', 'Payable', 'Owner debt'], rows: summaries(options) },
    { title: 'Truck Owners', filename: 'truck-owners', headers: ['Truck', 'Owner', 'Share %', 'Lent', 'Repaid', 'Owed'], rows: ownerRows(options) },
    { title: 'Truck Transactions', filename: 'truck-transactions', headers: ['Date', 'Truck', 'Owner', 'Where / Who', 'Type', 'Category', 'Details', 'Ref', 'Amount'], rows: transactionRows(options) });
  const transactionReport = (options: ExportBuildOptions) => choose(options,
    { title: 'Truck Summary', filename: 'truck-summary', headers: ['Truck', 'Unit', 'Cash', 'Income', 'Expenses', 'Net profit', 'Receivable', 'Payable', 'Owner debt'], rows: summaries(options) },
    { title: 'Truck Transactions', filename: 'truck-transactions', headers: ['Date', 'Truck', 'Owner', 'Where / Who', 'Type', 'Category', 'Details', 'Ref', 'Amount'], rows: transactionRows(options) },
    { title: 'Truck Transactions', filename: 'truck-transactions', headers: ['Date', 'Truck', 'Owner', 'Where / Who', 'Type', 'Category', 'Details', 'Ref', 'Amount'], rows: transactionRows(options) });
  return [
    { id: 'complete-statement', label: 'Complete statement', description: 'Truck balances, income, expenses, and owners', build: (options) => { const selected = statement(options); return report(selected.title, selected.filename, selected.headers, selected.rows, options); } },
    { id: 'owner-shares-loans', label: 'Owner shares and loans', description: 'Equity, loans, repayments, and money owed', build: (options) => choose(options, report('Truck Owner Summary', 'owner-summary', ['Truck', 'Owner', 'Share %', 'Lent', 'Repaid', 'Owed'], ownerRows(options), options), report('Truck Owner Details', 'owner-details', ['Truck', 'Owner', 'Share %', 'Lent', 'Repaid', 'Owed'], ownerRows(options), options), report('Truck Owner Transactions', 'owner-transactions', ['Date', 'Truck', 'Owner', 'Where / Who', 'Type', 'Category', 'Details', 'Ref', 'Amount'], transactionRows(options), options)) },
    { id: 'income-expenses', label: 'Income and expenses', description: 'Every trip, bill, loan, repayment, and cash movement', build: (options) => { const selected = transactionReport(options); return report(selected.title, selected.filename, selected.headers, selected.rows, options); } },
    { id: 'truck-summary', label: 'Truck summary', description: 'Condensed totals for each truck', build: (options) => { const selected = transactionReport(options); return report(selected.title, selected.filename, selected.headers, selected.rows, options); } },
    { id: 'transactions-by-truck-owner', label: 'Transactions by truck and owner', description: 'Full relational transaction breakdown', build: (options) => { const selected = transactionReport(options); return report(selected.title, selected.filename, selected.headers, selected.rows, options); } },
  ];
}
