import { supabase } from '../../lib/supabase';
import type { Owner, Transaction, Truck } from './types';
function explain(error: { message?: string; code?: string }) { if (error.code === '42P01' || error.code === 'PGRST205' || error.message?.toLowerCase().includes('could not find the table')) return new Error('Truck tables are not installed in Supabase yet. Run the Truck migrations, then refresh the app.'); return error; }
const truckFromDb = (r: Record<string, unknown>): Truck => ({ id: String(r.id), name: String(r.name ?? ''), unitNumber: String(r.unit_number ?? ''), makeModel: String(r.make_model ?? ''), vin: String(r.vin ?? ''), cashOnHand: Number(r.cash_on_hand ?? 0), licensePlate: String(r.license_plate ?? '') });
const ownerFromDb = (r: Record<string, unknown>): Owner => ({ id: String(r.id), truckId: String(r.truck_id), name: String(r.name ?? ''), startDate: String(r.start_date ?? ''), equityPercentage: Number(r.equity_percentage ?? 0), monthlyDrawRate: Number(r.monthly_draw_rate ?? 0), avatarColor: String(r.avatar_color ?? 'bg-slate-800 text-white') });
const transactionFromDb = (r: Record<string, unknown>): Transaction => ({ id: String(r.id), truckId: String(r.truck_id), date: String(r.occurred_on), type: r.transaction_type as Transaction['type'], category: String(r.category ?? ''), amount: Number(r.amount ?? 0), ownerId: r.owner_id ? String(r.owner_id) : undefined, description: String(r.description ?? ''), referenceNo: r.reference_no ? String(r.reference_no) : undefined });
export async function loadTruckData(workspaceId: string) { const [trucks, owners, transactions] = await Promise.all([supabase.from('trucks').select('*').eq('workspace_id', workspaceId).is('deleted_at', null).order('created_at'), supabase.from('truck_owners').select('*').eq('workspace_id', workspaceId).is('deleted_at', null).order('created_at'), supabase.from('truck_transactions').select('*').eq('workspace_id', workspaceId).is('deleted_at', null).order('occurred_on', { ascending: false })]); const error = trucks.error ?? owners.error ?? transactions.error; if (error) throw explain(error); return { trucks: (trucks.data ?? []).map((r) => truckFromDb(r as Record<string, unknown>)), owners: (owners.data ?? []).map((r) => ownerFromDb(r as Record<string, unknown>)), transactions: (transactions.data ?? []).map((r) => transactionFromDb(r as Record<string, unknown>)) }; }
export async function createTruck(workspaceId: string, v: Omit<Truck, 'id'>) { const { data, error } = await supabase.from('trucks').insert({ workspace_id: workspaceId, name: v.name, unit_number: v.unitNumber, make_model: v.makeModel, vin: v.vin, cash_on_hand: v.cashOnHand, license_plate: v.licensePlate }).select('*').single(); if (error) throw error; return truckFromDb(data); }
export async function createTruckOwner(workspaceId: string, v: Omit<Owner, 'id'> & { userId?: string | null }) { const { data, error } = await supabase.from('truck_owners').insert({ workspace_id: workspaceId, truck_id: v.truckId, user_id: v.userId ?? null, name: v.name, start_date: v.startDate, equity_percentage: v.equityPercentage, monthly_draw_rate: v.monthlyDrawRate, avatar_color: v.avatarColor }).select('*').single(); if (error) throw error; return ownerFromDb(data); }
export async function updateTruckOwner(workspaceId: string, v: Owner) { const { data, error } = await supabase.from('truck_owners').update({ truck_id: v.truckId, name: v.name, start_date: v.startDate, equity_percentage: v.equityPercentage, monthly_draw_rate: v.monthlyDrawRate, updated_at: new Date().toISOString() }).eq('workspace_id', workspaceId).eq('id', v.id).select('*').single(); if (error) throw error; return ownerFromDb(data); }
export async function updateTruck(workspaceId: string, v: Truck) { const { data, error } = await supabase.from('trucks').update({ name: v.name, unit_number: v.unitNumber, make_model: v.makeModel, vin: v.vin, cash_on_hand: v.cashOnHand, license_plate: v.licensePlate, updated_at: new Date().toISOString() }).eq('workspace_id', workspaceId).eq('id', v.id).select('*').single(); if (error) throw error; return truckFromDb(data); }
export async function deleteTruck(workspaceId: string, id: string) { const { error } = await supabase.from('trucks').update({ deleted_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq('workspace_id', workspaceId).eq('id', id).is('deleted_at', null); if (error) throw error; }
export async function createTruckTransaction(workspaceId: string, v: Omit<Transaction, 'id'>) { const { data, error } = await supabase.from('truck_transactions').insert({ workspace_id: workspaceId, truck_id: v.truckId, owner_id: v.ownerId ?? null, occurred_on: v.date, transaction_type: v.type, category: v.category, amount: v.amount, description: v.description, reference_no: v.referenceNo ?? null }).select('*').single(); if (error) throw error; return transactionFromDb(data); }
export async function updateTruckTransaction(workspaceId: string, v: Transaction) { const { data, error } = await supabase.from('truck_transactions').update({ truck_id: v.truckId, owner_id: v.ownerId ?? null, occurred_on: v.date, transaction_type: v.type, category: v.category, amount: v.amount, description: v.description, reference_no: v.referenceNo ?? null, updated_at: new Date().toISOString() }).eq('workspace_id', workspaceId).eq('id', v.id).is('deleted_at', null).select('*').single(); if (error) throw error; return transactionFromDb(data); }
export async function softDeleteTruckTransaction(workspaceId: string, id: string) { const { error } = await supabase.rpc('delete_truck_transaction', { target_workspace: workspaceId, target_transaction: id, approval_id: null }); if (error) throw error; }
export async function deleteTruckOwner(workspaceId: string, id: string) { const { error } = await supabase.from('truck_owners').update({ deleted_at: new Date().toISOString() }).eq('workspace_id', workspaceId).eq('id', id); if (error) throw error; }
export async function loadTruckWorkspaceMembers(workspaceId: string) { const { data, error } = await supabase.rpc('list_workspace_members', { target_workspace: workspaceId }); if (error) throw error; return (data ?? []) as Array<{ user_id: string; email: string; display_name: string }>; }
