import type { Employee, Transaction } from './types';
import { calculateEmployeeAccrual, getTodayString } from './utils/calc';
import type { ExportBuildOptions, ExportReportDefinition } from '../../lib/exports/exportTypes';
import { formatExportNumber } from '../../lib/exports/numberFormatting';

type PayrollExportData = { employees: Employee[]; transactions: Transaction[]; asOfDate?: string };
const money = formatExportNumber;
const inRange = (date: string, options: ExportBuildOptions) => (!options.startDate || date >= options.startDate) && (!options.endDate || date <= options.endDate);

export function buildPayrollExportReports(data: PayrollExportData): ExportReportDefinition[] {
  const asOf = data.asOfDate ?? getTodayString();
  const employeeById = new Map(data.employees.map((employee) => [employee.id, employee]));
  const employees = (options: ExportBuildOptions) => data.employees.filter((employee) => { const query = options.query?.trim().toLowerCase(); return (!options.entityId || employee.id === options.entityId) && (!query || `${employee.name} ${employee.department ?? ''}`.toLowerCase().includes(query)); });
  const summaries = (options: ExportBuildOptions) => employees(options).map((employee) => { const summary = calculateEmployeeAccrual(employee, data.transactions, options.endDate ?? asOf); return [employee.name, employee.status, employee.startDate, money(summary.currentMonthlySalary), money(summary.totalAccruedWages), money(summary.totalWithdrawn), money(summary.remainingBalance)]; });
  const payrollSummary = (options: ExportBuildOptions) => employees(options).reduce((totals, employee) => { const summary = calculateEmployeeAccrual(employee, data.transactions, options.endDate ?? asOf); totals.monthly += summary.currentMonthlySalary; totals.earned += summary.totalAccruedWages; totals.paid += summary.totalWithdrawn; totals.balance += summary.remainingBalance; return totals; }, { monthly: 0, earned: 0, paid: 0, balance: 0 });
  const summaryItems = (options: ExportBuildOptions) => { const summary = payrollSummary(options); return [{ label: 'Monthly pay', value: money(summary.monthly) }, { label: 'Earned', value: money(summary.earned), tone: 'positive' as const }, { label: 'Paid', value: money(summary.paid), tone: 'negative' as const }, { label: 'Owed', value: money(summary.balance) }]; };
  const displayType = (type: string) => type === 'withdrawal' ? 'Paid' : type === 'raise' ? 'Pay change' : type;
  const transactionRows = (options: ExportBuildOptions) => data.transactions.filter((tx) => { const query = options.query?.trim().toLowerCase(); const text = `${tx.employeeName ?? employeeById.get(tx.employeeId)?.name ?? ''} ${tx.referenceNo ?? ''} ${tx.notes ?? ''}`.toLowerCase(); return (!options.entityId || tx.employeeId === options.entityId) && (!options.transactionType || tx.type === options.transactionType) && (!query || text.includes(query)) && inRange(tx.date, options); }).sort((a, b) => b.date.localeCompare(a.date)).map((tx) => [tx.date, employeeById.get(tx.employeeId)?.name ?? tx.employeeName ?? 'Unknown name', displayType(tx.type), tx.referenceNo ?? '', tx.notes ?? '', money(tx.amount)]);
  const paymentSummaryRows = (options: ExportBuildOptions) => { const rows = new Map<string, { count: number; total: number }>(); transactionRows(options).forEach((row) => { const name = String(row[1]); const current = rows.get(name) ?? { count: 0, total: 0 }; current.count += 1; current.total += Number(row[5]); rows.set(name, current); }); return Array.from(rows, ([name, summary]) => [name, summary.count, money(summary.total)]); };
  const detailedEmployees = (options: ExportBuildOptions) => employees(options).flatMap((employee) => { const summary = calculateEmployeeAccrual(employee, data.transactions, options.endDate ?? asOf); const header = [[employee.name, employee.startDate, employee.status, money(summary.currentMonthlySalary), money(summary.totalAccruedWages), money(summary.totalWithdrawn), money(summary.remainingBalance)]]; const details = data.transactions.filter((tx) => tx.employeeId === employee.id && inRange(tx.date, options)).map((tx) => [employee.name, tx.date, tx.type, money(tx.amount), tx.paymentMethod ?? '', tx.referenceNo ?? '', tx.notes ?? '']); return [...header, ...details]; });
  const employeeDateRange = (options: ExportBuildOptions) => { const selected = employees(options); return { startDate: selected.map((employee) => employee.startDate).sort()[0], endDate: options.endDate ?? asOf }; };
  const report = (title: string, filename: string, headers: string[], rows: Array<Array<string | number>>, options: ExportBuildOptions, summary = summaryItems(options), dateRange?: { startDate?: string; endDate?: string }) => ({ title, filename, headers, rows, summary, dateRange, lines: rows.map((row) => row.join(' | ')) });
  return [
    { id: 'employees-condensed', label: 'Names summary', description: 'Pay totals for each person', build: (options) => report('Payroll Summary', 'payroll-summary', ['Name', 'Status', 'Start', 'Rate', 'Earned', 'Paid', 'Owed'], summaries(options), options, summaryItems(options), employeeDateRange(options)) },
    { id: 'employees-detailed', label: 'Names and payments', description: 'Each person with payments below', build: (options) => options.detail === 'condensed' ? report('Payroll Summary', 'payroll-summary', ['Name', 'Status', 'Start', 'Rate', 'Earned', 'Paid', 'Owed'], summaries(options), options, summaryItems(options), employeeDateRange(options)) : options.detail === 'full' ? report('Payroll Payments', 'payroll-payments', ['Date', 'Name', 'Entry', 'Ref', 'Notes', 'Amount'], transactionRows(options), options, summaryItems(options), employeeDateRange(options)) : report('Payroll Details', 'payroll-details', ['Name', 'Date', 'Type', 'Amount', 'Earned', 'Paid', 'Notes'], detailedEmployees(options), options, summaryItems(options), employeeDateRange(options)) },
    { id: 'salary-raises', label: 'Pay changes', description: 'Pay changes and dates', build: (options) => { const rows = employees(options).flatMap((employee) => employee.salaryHistory.filter((raise) => inRange(raise.effectiveDate, options)).map((raise) => [employee.name, raise.effectiveDate, money(raise.newMonthlySalary), raise.reason])); return report('Payroll Pay Changes', 'pay-changes', ['Name', 'Date', 'New rate', 'Reason'], rows, options); } },
    { id: 'payments-withdrawals', label: 'Payments', description: 'Every payment', build: (options) => options.detail === 'condensed' ? report('Payroll Payment Summary', 'payment-summary', ['Name', 'Payments', 'Total'], paymentSummaryRows(options), options, summaryItems(options)) : report('Payroll Payments', 'payments', ['Date', 'Name', 'Entry', 'Ref', 'Notes', 'Amount'], transactionRows(options), options, summaryItems(options)) },
  ];
}
